<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
    <RootNamespace>Core.DemoSeeder</RootNamespace>
    <RollForward>LatestMajor</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Services\CoreService\Core.Persistence\Core.Persistence.csproj" />
    <ProjectReference Include="..\..\src\Services\CoreService\Core.Domain\Core.Domain.csproj" />
  </ItemGroup>

</Project>
